### ISSUE TITLE
Add .Net Core Support

### ISSUE THREAD

**Issue by colin-young** [wikibus/Rdf.Vocabularies#2]
Looks like it should just need a new build target, but I don't have access to VS 2015 on Windows at the moment to try that out, due to the modeling tools requirement.

**Comment by tpluscode** [comment]
Yeah, this one will be a lot easier than the others but I have to replace T4 templates which build vocab classes from OWL/RDF. I've found [Scripty](https://github.com/daveaglick/Scripty), which should help. I'll gladly replace the text templates with actual C# code. Could even use dotNetRDF to process the vocabularies :)

**Comment by colin-young** [comment]
That seems like it might result in a more powerful solution. Again, let me know how I can help out with this effort. It would be a good way to get my feet wet with RDF and vocabularies.

**Comment by tpluscode** [comment]
I'm almost done now but maybe you could actually help me with one issue. 

I'm trying to generate the C# files from vocabularies right before build. In "old" MSBuild I imported T4 task. Now in `xproj` I tried adding a target like below but it's always executed after building the project.

``` xml
<Target Name="Scripty" BeforeTargets="Build">
    <Exec Command="..\packages\Scripty\tools\Scripty.exe ScriptFilePaths Vocabs.csx" />
</Target>
```

How can this be done? Or maybe I should just ignore it for now and wait for `csproj` to come back for good?

**Comment by colin-young** [comment]
I've been playing with the latest preview 4 CLI build chain. I'll take a
look in a few hours after I get home and see what I can figure out with the
new csproj format.

**Comment by colin-young** [comment]
This pattern works for me in a simple web api project I converted from `project.json` to the new `csproj` format (.Net CLI, VS 2017, VS OS X):

```
<Target Name="PrecompileScript" BeforeTargets="BeforeBuild" Condition=" '$(IsCrossTargetingBuild)' != 'true' ">
    <Exec Command="echo ==== Pre Compile ====" />
  </Target>
```

I think if you just use:

```
<Target Name="PrecompileScript" BeforeTargets="BeforeBuild">
    <Exec Command="..\packages\Scripty\tools\Scripty.exe ScriptFilePaths Vocabs.csx" />
  </Target>
```

That will probably do it, but you might need to be using VS 2017 or the CLI to build. Maybe it will work in `.xproj`?

**Comment by tpluscode** [comment]
Uh, I tried installing VS2017 but installed kind of corrupt. I got no project templates. And it doesn't open `.xproj` anymore while the old `.csproj` opens as usual. I expected some kind of migration. Guess I'll have to wait for that.

But maybe it is `BeforeBuild` and not `Build`. I will try that in the evening

**Comment by colin-young** [comment]
Ha ha. I should have looked for a new branch last night. I pulled down `net-core` this morning, created a `project.json` and did a migrate. I added the Scripty MsBuild reference, and now I'm getting errors from that. I'll need to follow up with that project to see if it will run on non-Windows platforms. I'll push the changes to my fork at the end of the day so you can take a look. I think it should work on Windows, but you might need to run it via the CLI or VS Code.

**Comment by tpluscode** [comment]
I don't think Scripty.MSBuild can work cross-platform yet. I am running the CLI (like in the xproj above)

**Comment by colin-young** [comment]
I added `Scripty.MsBuild` as the package reference and it looked like it was trying to run before the compile. With the file globbing support in the new project file it should pick up newly generated files, but referencing the file name should work also for older project formats. The package appears to automatically insert itself into the build, but I didn't see a change in the `csproj` file.

**Comment by tpluscode** [comment]
If only it worked for me locally. Which is unfortunate because the `preview2` state of dotnet is far from great. It almost works for me. The last problem is that `dotnet pack` takes the version from `package.json` and it is not possible to provide it at build time other that modify the file 🔨.

**Comment by colin-young** [comment]
With preview 4 I am able to set the version in the `csproj` in the `PropertyGroup` with `VersionPrefix` and `PackageId`. That still doesn't solve the build time, but you can provide `--version-suffix` to pack.

The documentation leaves a bit to be desired. I only figured that out from a [gist](https://gist.github.com/natemcmaster/2eb494cf07771f70825ba72a3e15c444) on a bug report.

**Comment by tpluscode** [comment]
I found this `dotnet-version` tool, mentioned in dotnet/cli#2676, which solves the version issue. True, the state of .NET leaves a lot to be desired.

Anyway, I think I will have a prerelease package ready soon

**Comment by tpluscode** [comment]
@colin-young version `1.2.1-core0001` should be ready to download soon. please tell me if it's working for you

**Comment by colin-young** [comment]
Thanks. I'll check it out tonight.

**Comment by colin-young** [comment]
Looks good. Running on OS X:

    static void Main(string[] args)
    {
        var rdfsLabel = Rdfs.label;
        Console.WriteLine("Hello World!");

        Console.WriteLine($"rdfsLabel: {rdfsLabel.ToString()}");
    }

Gives me:

    Hello World!
    rdfsLabel: http://www.w3.org/2000/01/rdf-schema#label

**Comment by tpluscode** [comment]
It's funny how much effort it took to build some static classes 😉
