### ISSUE TITLE
v1.2.1-core0001 missing several definitions

### ISSUE THREAD

**Issue by colin-young** [wikibus/Rdf.Vocabularies#6]
In particular, `Hydra` does not contain a definition for:

* Collection
* entrypoint
* expects
* PartialCollectionView
* Resource
* supportedClass
* supportedOperation
* supportedProperty

It appears to be due to the `rdf:type`. If I change it to `<rdf:type rdf:resource="http://www.w3.org/ns/hydra/core#Class"/>` from the current `<rdf:type rdf:resource="http://www.w3.org/ns/hydra/core#Link"/>` I get the properties generated in `Hydra.cs`, however, I don't know nearly enough about RDF to know if that is the correct solution or even a good one.

**Comment by tpluscode** [comment]
Ah, good catch. The script which processes the RDF ignores the class hierarchy.

**Comment by tpluscode** [comment]
@colin-young before I push this I'd like sanity check on dropping .NET Portable. The only target coming from master is now .NET Standard 1.1 and thus .NET Framework 4.5. Do you agree?

**Comment by colin-young** [comment]
Thanks. That seems to have solved the issue.

And yes, that's my understanding of .Net Standard 1.1.

**Comment by tpluscode** [comment]
All right. Published as 1.3
